apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      role: client-website
  template:
    metadata:
      labels:
        role: client-website
    spec:
      containers:
      - name: client-website
        image: erickalv/sopes:front
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: website-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    role: client-website