version: "3.9"
services:
  pythonapp:
    build: ./Back/
    command: sh -c "sleep 15s ; python3 -m flask run --host=0.0.0.0"
    depends_on:
      - mysql
    ports:
      - "5000:5000"


  mysql:
    build: ./DB/
    restart: always
    ports:
      - "3306:3306"
