# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

#Estas dos lineas de comando son importantes en cloud run
ENV PORT 5000
ENV HOST 0.0.0.0

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
EXPOSE 5000
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]