# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

ENV MYSQL_HOST mysql
ENV MYSQL_USER root
ENV MYSQL_PASSWORD root
ENV MYSQL_NAME db

WORKDIR /python-docker

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN python -m pip install mysql-connector-python

COPY . .
EXPOSE 5000
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]